ibm.mq.channel=P_PEN
ibm.mq.connName=mpls03.adeo.no(1414)
ibm.mq.queueManager=MPLS03

ibm.mq.user=${srvpenmq.username}
ibm.mq.password=${srvpenmq.password}

samhandler.xml.queueName=queue:///QA.P415.AS10_SAMHANDLER_SERVICE?targetClient=1

tss.samhandlerv2.endpoint.url=https://wasapp.adeo.no/services/tss/hentSamhandler
