name: "Build and deploy"

on:
  push

jobs:
  build:
    permissions:
      contents: "read"
      checks: "write"
      id-token: "write"
      packages: "write"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      version: ${{ steps.version.outputs.version }}
      image: ${{ steps.docker_push.outputs.image }}

    steps:
      - uses: actions/checkout@v7

      - name: Set version
        id: version
        shell: bash
        run: |
          TIME=$(TZ="Europe/Oslo" date +%Y.%m.%d-%H.%M)
          COMMIT=$(git rev-parse --short=12 HEAD)
          export VERSION="$TIME-$COMMIT"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build
        shell: bash
        run: |
          mvn -Drevision="${VERSION}" package
        env:
          TZ: "Europe/Oslo"

      - name: Upload surefire reports on failure
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: surefire-reports
          path: ${{ github.workspace }}/**/target/surefire-reports/*
          retention-days: 5

      - name: Upload HotSpot Fatal Error logs on failure
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: hotspot-fatal-error-logs
          path: ${{ github.workspace }}/**/hs_err_pid*.log
          retention-days: 5

      - name: "Build and publish Docker image"
        if: ${{ github.actor != 'dependabot[bot]' }}
        id: docker_push
        uses: nais/docker-build-push@v0
        with:
          team: pensjondeployer
          tag: ${{ env.VERSION }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

  deploy:
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write
    needs: [build]
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v7
      - uses: nais/deploy/actions/deploy@v2
        env:
          IMAGE: "${{ needs.build.outputs.image }}"
          RESOURCE: .nais/nais.yaml
          CLUSTER: 'prod-fss'
          VAR: "version=${{ needs.build.outputs.version }}"
          VARS: '.nais/vars-prod.yaml'

  deploySandbox:
    if: github.ref == 'refs/heads/sandbox' || github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write
    needs: [build]
    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        include:
          - env: q1
          - env: q2

    steps:
      - uses: actions/checkout@v7
      - uses: nais/deploy/actions/deploy@v2
        env:
          IMAGE: "${{ needs.build.outputs.image }}"
          RESOURCE: .nais/nais.yaml
          CLUSTER: 'dev-fss'
          VAR: "version=${{ needs.build.outputs.version }}"
          VARS: '.nais/vars-dev-${{matrix.env}}.yaml'

  deployQ0andQ5:
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write
    needs: [build]
    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        include:
          - env: q0
          - env: q5

    steps:
      - uses: actions/checkout@v7
      - uses: nais/deploy/actions/deploy@v2
        env:
          IMAGE: "${{ needs.build.outputs.image }}"
          RESOURCE: .nais/nais.yaml
          CLUSTER: 'dev-fss'
          VAR: "version=${{ needs.build.outputs.version }}"
          VARS: '.nais/vars-dev-${{matrix.env}}.yaml'
